### ISSUE TITLE
Dub Ban crashes the bot

### ISSUE THREAD

**Issue by dorkix** [avatarkava/beavisbot-dubtrack-fm#115]
Hey, after banning someone from the room, doing .idle crashes the bot with following error:

`at emitOne (events.js:77:13) at IncomingMessage.<anonymous> (/home/ubuntu/workspace/node_modules/dubapi/node_modules/pubnub/node.js/pubnub.js:2259:17) at doNTCallback2 (node.js:429:9) at process._tickCallback (node.js:343:17))` 

and sometimes banning someone crashes the bot without doing any other command with following error

` TypeError: Cannot read property 'username' of undefined at IncomingMessage.<anonymous> (/home/ubuntu/workspace/node_modules/dubapi/node_modules/pubnub/node.js/pubnub.js:2259:17) at doNTCallback2 (node.js:429:9) at process._tickCallback (node.js:343:17)` 

I think new dubapi and dubtrack updates might have screwed something.

Also whoever executes ban bot recognizes them as they left the room along with banned user even though they are still in the room

It doesn't give any more info other than that.

**Comment by avatarkava** [comment]
Is that the full stack trace (error message) you're getting on both those?  They look incomplete.

**Comment by dorkix** [comment]
Yes i copy pasted everything that spits out in the terminal window when bot crashes.

**Comment by dorkix** [comment]
UPDATE : after trying to reproduce this crash as best as i can, theres new exception  stack : 
`Async._drainQueues (/home/ubuntu/workspace/node_modules/sequelize/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.__dirname.drainQueues [as _onImmediate] (/home/ubuntu/workspace/node_modules/sequelize/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)`

`at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:166:7)`


`Process exited with code: 1`

PS. Crash occurs ONLY after doing ANY  [.] command AFTER banning someone.

**Comment by dorkix** [comment]
Heres the terminal log after ban (sry for the formatting im really bad at this) error stack from prev comment disappeared for some reason but this showed : 
[CHAT] manzorx: okies try ban now                                                                                                                                
                                                                                                                                                                                                                                                     at SELF.subscribe.xdr.success (/home/ubuntu/workspace/node_modules/dubapi/node_modules/pubnub/core/pubnub-common.js:1533:25)
    at finished (/home/ubuntu/workspace/node_modules/dubapi/node_modules/pubnub/node.js/lib/xdr.js:60:5)
    at SELF.subscribe.xdr.success (/home/ubuntu/workspace/node_modules/dubapi/node_modules/pubnub/core/pubnub-common.js:1533:25)
    at finished (/home/ubuntu/workspace/node_modules/dubapi/node_modules/pubnub/node.js/lib/xdr.js:60:5)
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/node_modules/dubapi/node_modules/pubnub/node.js/lib/xdr.js:152:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)`
    at process._tickCallback (node.js:343:17)


Process exited with code: 1

**Comment by dorkix** [comment]
Any news about this problem? Thought it might be on dub's end because of updates but it is still broken, is the info i provided above(screenshot) satisfactory?
